version: "2"

run:
  timeout: "5m"
  tests: true

linters:
  exclusions:
    paths:
      - "docs"
  enable:
      - errcheck
      - sqlclosecheck

      - govet
      - staticcheck
      - ineffassign
      - unused
      - dupl
      - gocyclo
      - goconst

      - nakedret

      - contextcheck
issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  fix: false
  uniq-by-line: true
  whole-files: false

output:
  sort-order:
    - severity
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true
