{
 "title": "Business Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "User Activity Changes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(user_status_changes_total) by (operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Business Errors Breakdown",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (business_errors_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Business Errors Total",
   "type": "stat",
   "gridPos": { "h": 16, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(business_errors_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(users_created_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Pull Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pr_created_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Merge Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pr_merged_total) / sum(pr_created_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Teams",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(teams_created_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Goroutines Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Go Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "alloc bytes" },
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "heap alloc bytes" },
    { "expr": "go_memstats_heap_sys_bytes", "legendFormat": "heap sys bytes" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{container=\"pr-service\"}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "Quantile: {{quantile}}" }
   ]
  }
 ]
}